name: api_estabelecimentos

version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres-postgis
    restart: always
    environment:
      POSTGRES_DB: geo_db
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgis.sql:/docker-entrypoint-initdb.d/z-init-postgis.sql
      - ./scripts/02-seed-tipos.sql:/docker-entrypoint-initdb.d/02-seed-tipos.sql

volumes:
  postgres_data:
